### ISSUE TITLE
Support WebRTC data channel, or general transport mechanism

### ISSUE THREAD

**Issue by maun** [amethyst/laminar#111]
I would like to use this for a webassembly game. What would be needed to support the WebRTC data channel?

Ideally I would implement some trait and laminar uses my transport mechanism, this would also be useful for simulated networks.

**Comment by TimonPost** [comment]
Thanks for taking the time to look into this crate. Although it sounds really cool I don't think we will implement it any time soon. As you might know, this crate is currently developed for amethyst and we first try to prioritize the work that needs to be done first.

As far as it goes about custom processing, I like that idea and we will see what we can do with it.

 I let this issue open to see what we can do in the future. And to hear other peoples opinions.

**Comment by maun** [comment]
Sure, I might give it a try (but probably not right now). Any suggestions for the design?

**Comment by TimonPost** [comment]
This can be closed, sorry we have never responded to this. But supporting WebRTC will be done at amethyst_network level, and not with laminar.

**Comment by kyren** [comment]
> But supporting WebRTC will be done at amethyst_network level, and not with laminar.

May I ask how this will work?  I was considering using laminar as a reliability layer where on desktop it would use UDP, but on wasm it might use [webrtc-unreliable](https://github.com/kyren/webrtc-unreliable), and on platforms like steam it might use steam's built-in P2P networking.

I realize that both my examples of WebRTC and Steam have their own reliability systems in addition to their UDP-like (unreliable, unordered) parts, but for several reasons this is less ideal than using a single reliability system on top of all of them:

1) WebRTC as a standard is very complex, so getting reliability between a browser and a server requires implementing the rest of SCTP and this is quite hard
2) Steam P2P networking does not (as far as I remember) give you things like reliable-unordered messages or separate channels
3) Probably most importantly, making an abstraction that sits on top of several different reliability protocols means dealing with N different unique sets of networking behavior rather than just 1
4) There are more platforms for video games than this, and some even preclude using direct networking at all, but all of them have some kind of unreliable, unordered (UDP-like) transport system.

I'd happily consider using laminar if this was changed!

**Comment by jstnlef** [comment]
Laminar will not support a general transport mechanism because it, itself, is the transport mechanism. You can think of laminar as another protocol like UDP or TCP but implemented in user land code.

**Comment by kyren** [comment]
> Laminar will not support a general transport mechanism because it, itself, is the transport mechanism. You can think of laminar as another protocol like UDP or TCP but implemented in user land code.

That doesn't make a lot of sense, laminar sends UDP packets using std::net::UdpSocket, certainly it could allow for other UDP-like transports as well.

I mean if the answer is just "no" that's fine, but I think there's a general desire for a library that allows you to add customizable reliability on top of an unreliable packet interface.

**Comment by jstnlef** [comment]
Ah I see. I think that I may have misunderstood your initial comment. What you're looking for is for us to separate out the protocol layer from the underlying socket implementation rather than, what I originally thought, which was provide support for using already reliable protocols as the underlying implementation for laminar. In the long run, we're definitely going to want to do this and it should likely be able to support your use case. Also, it'll let us easily write a much more thorough test suite of the protocol implementation proper.

**Comment by LucioFranco** [comment]
I'd really like to see this type of abstraction! 😄
