### ISSUE TITLE
Switch protocol version to CRC16.

### ISSUE THREAD

**Issue by TimonPost** [amethyst/laminar#152]
Protocol version is currently a CRC32, we could save two bytes by making it a CRC16.

I saw [this](https://forums.intel.com/s/question/0D50P00003yyG94SAE/16bit-crc-vs-32bit-crc?language=en_US)

So basically a CRC32 can cover 500MBytes and a CRC16 can cover: 8kBytes.

- Protocol version is located in the [StandardHeader](https://github.com/amethyst/laminar/blob/master/src/packet/header/standard_header.rs#L14)
- CRC32 is calculated [here](https://github.com/amethyst/laminar/blob/master/src/protocol_version.rs)

**Comment by daxpedda** [comment]
Have a couple of suggestions here:
- Instead of using CRC16 we could just use a counter, 16 bits would leave us with 65,535 distinct versions
- Instead of putting the protocol version in every package header, a simple handshake or the first package sent can include the protocol version, which is a feature that can be implemented in the future, doesn't prevent us from changing to CRC16 until then

**Comment by jstnlef** [comment]
So, as the checksum stands now, we're better off not having it or only including a byte or 2 to represent the version numbering. However, the way this should have always worked is that the checksum would be calculated based on a version string + the payload. This allows us to both verify that a valid client is sending us data and that packets (both fragmented and otherwise) have arrived at the destination as they were sent.
