### ISSUE TITLE
Clean up code base

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/laminar#31]
Steps:
- [x] Run Clippy and fix suggestions
- [x] Clean up warnings in the crate, test, and examples
- [x] Rustfmt the repo with `v0.99`

**Comment by TimonPost** [comment]
Updates #31 en #32

**Comment by CBenoit** [comment]
I already mentioned it here: https://github.com/amethyst/laminar/pull/44
But I feel like `packet/header/packet.rs` should be renamed to `packet/header/packet_header.rs`.
I consider it to be clearer:
- I regularly open the wrong file because it is named like `packet/packet.rs`
- It doesn't contains Packet but PacketHeader. When I read the codebase the first time it was confusing.

**Comment by TimonPost** [comment]
Do it, I first called that way since it was in the header folder so thought it was unnecessarily to add `_header` to it. But I find it confusing to so i'll be fine with it.

**Comment by TimonPost** [comment]
This is an ongoing process but for now we did #36 , #57
