### ISSUE TITLE
Re-work client counting to return a result

### ISSUE THREAD

**Issue by fhaynes** [amethyst/laminar#67]
```rust
    pub fn count(&self) -> usize {
         match self.connections.read() {
             Ok(connections) => { connections.len() },
             Err(_) => { 0 },
```
Should probably return a result, not swallow the error and return 0.

**Comment by TimonPost** [comment]
One thing I don't like about this have you ever called a `count()` function which returns a result? I didn't. I find it a weird idea that something simple like `count()` can go wrong. So an alternative would be to add a counter to the connection pool who is counting the connections. This way we don't have to acquire the read lock at all.

**Comment by fhaynes** [comment]
Well, my primary concern is that it returns 0 if there is an error, which could also be a valid number of connections. In C-land, I'd suggest returning -1. How about Option<usize>?

**Comment by TimonPost** [comment]
Indeed you are right with it that there could be `0` connections. I like `Option` more. But why not have a counter for the connections. Who will increase when incoming connection and decreases when connections times out. Then if the user wants to request the connected clients it could never fail and there is no lock needed.

**Comment by fhaynes** [comment]
Even better! Sorry, hadn't had coffee and missed that part earlier.

**Comment by LucioFranco** [comment]
@TimonPost yes, I think that is a good solution 👍

**Comment by TimonPost** [comment]
I've done some things but since clients is added from within the timeout thread we can not access the counter from `ConnectionPool` other than using an `Arc` with `Mutex`. But since this will also be error-prone when getting the count we need a redisgn. 

We should move the connection thread out of `ConnectionPool`. Because I want to have `ConnectionPool` to be one type with one responsibility. 

Connection pool should have the following methods:

```
get_connection_or_insert();
remove_by_address();
count();
```

Next, the timeout loop currently inside the connection pool should be placed somewhere else. This way we can handle the client count. Like when function `remove_by_address()` is called we decrement the client count and when `get_connection_or_insert()` we increment the client count. The connection manager has ownership of its internals. And the timeout thread is not responsible for updating the client count.

**Comment by TimonPost** [comment]
#101 fixes it
